notify:
  send: false        # Set to false to disable desktop notifications
  type: desktop     # This must be set to 'desktop' for now

hyperparameters:
  logistic_ovr:
    - max_iter: 1000
      multi_class: 'ovr'
    - max_iter: 500
      multi_class: 'ovr'
  logistic_multinomial:
    - max_iter: 1000
      multi_class: 'multinomial'
      solver: 'lbfgs'
    - max_iter: 500
      multi_class: 'multinomial'
      solver: 'lbfgs'
  knn:
    - n_neighbors: 5
    - n_neighbors: 7
  svm:
    - C: 1.0
      kernel: 'rbf'
      gamma: 'scale'
    - C: 0.5
      kernel: 'linear'
      gamma: 'scale'
  random_forest_classifier:
    - n_estimators: 100
      max_depth: 10
      random_state: 42
    - n_estimators: 200
      max_depth: 10
      random_state: 42
  extra_trees_classifier:
    - n_estimators: 100
      max_depth: 10
      random_state: 42
    - n_estimators: 200
      max_depth: 10
      random_state: 42
  naive_bayes:
    - {}

